adapters:
- config:
    enable_webui: true
    webui_token: R3wJfA6WyLN.LpxK
    webui_uri: http://127.0.0.1:6099
    ws_token: napcat_ws
    ws_listen_ip: 127.0.0.1
    ws_uri: ws://127.0.0.1:3002
  enabled: true
  platform: qq
  type: napcat
bot_uin: '3644596926'
check_ncatbot_update: true
debug: false
enable_webui_interaction: true
logging:
  event_log_format: summary
  event_log_levels:
    meta_event: NONE
plugin:
  auto_install_pip_deps: true
  builtin_commands:
    config_toggle: true
    load: true
    reload: true
    sysinfo: true
    unload: true
  builtin_commands_group_allowed: false
  enable_builtin_commands: true
  hot_reload: true
  load_plugin: true
  plugin_blacklist: []
  plugin_configs:
    qq_recorder:
      monitor_all: false
      targets:
        groups: ["1072706649"]
        private: ["2162371684"]
      storage:
        database: data/recorder.db
        images_dir: data/images
      image:
        download: true
        timeout: 60
        max_file_size: 209715200
      forward:
        max_depth: 8
        parse_content: true
      backup:
        enabled: true
        output_dir: data/backups
        keep_last: 7
        full_interval_days: 7
        full_time: "14:00"
        incremental_times:
          - "12:00"
          - "18:00"
          - "23:00"
  plugin_whitelist: []
  plugins_dir: plugins
  skip_pip_install_confirm: false
root: '2162371684'
skip_napcat_install_confirm: false
skip_ncatbot_install_check: false
websocket_timeout: 15

